# Generated by Django 6.0.3 on 2026-03-19 02:23

from decimal import Decimal
from django.db import migrations, models


FIXED_TICKET_TYPES = [
    ("Standard", Decimal("500000.00")),
    ("Premium", Decimal("1000000.00")),
    ("VIP", Decimal("1500000.00")),
]


def normalize_ticket_types(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    TicketType = apps.get_model("events", "TicketType")

    for event in Event.objects.all():
        TicketType.objects.filter(event=event).delete()

        for ticket_name, ticket_price in FIXED_TICKET_TYPES:
            TicketType.objects.create(
                event=event,
                name=ticket_name,
                price=ticket_price,
                quantity_total=200,
                quantity_sold=0,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='price',
            field=models.DecimalField(choices=[(Decimal('500000.00'), '500000 VND'), (Decimal('1000000.00'), '1000000 VND'), (Decimal('1500000.00'), '1500000 VND')], decimal_places=2, max_digits=10),
        ),
        migrations.RunPython(normalize_ticket_types, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='tickettype',
            constraint=models.UniqueConstraint(fields=('event', 'price'), name='unique_ticket_price_per_event'),
        ),
        migrations.AddConstraint(
            model_name='tickettype',
            constraint=models.CheckConstraint(condition=models.Q(('price__in', [Decimal('500000.00'), Decimal('1000000.00'), Decimal('1500000.00')])), name='ticket_price_is_allowed_option'),
        ),
    ]
